apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-4
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: test-volume-4
      mountPath: /data/
  volumes:
  - name: test-volume-4
    persistentVolumeClaim:
      claimName: test4-pvc
